# Generated by Django 2.0 on 2018-01-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFOC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakelompok',
            name='nama_kel',
            field=models.CharField(max_length=60),
        ),
    ]
