# Generated by Django 2.0.1 on 2018-01-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataKelompok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kel', models.CharField(blank=True, max_length=60)),
                ('guru_pem', models.CharField(max_length=60)),
                ('asalSekolah', models.CharField(max_length=60)),
                ('alamatSekolah', models.CharField(max_length=200)),
                ('noTelpSekolah', models.CharField(max_length=14)),
                ('noTelpGuru', models.CharField(max_length=14)),
                ('noTelpKetua', models.CharField(max_length=14)),
                ('mailGuru', models.CharField(max_length=100)),
                ('mailKetua', models.CharField(max_length=100)),
                ('idLine', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dataPeserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_leng', models.CharField(max_length=60)),
                ('nis', models.IntegerField(default=0)),
                ('dataKel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='I2C.dataKelompok')),
            ],
        ),
    ]
