# Generated by Django 2.0.1 on 2018-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I2C', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapeserta',
            name='nis',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
